import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/header'
import HamburgerMenu from "../components/HamburgerMenu"
import Footer from "../components/footer"
import Hero from "../components/hero"
import ToButton from "../components/ToButton"
import Mission from "../components/mission"
import AboutMe from "./AboutMe"
import Contact from "../components/Contact"
import { client } from '../libs/client'
import NewsList from './NewsList'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>yuj yoga&bodymakeup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HamburgerMenu />
      <Hero />
      <NewsList />
      <Mission title={"Vital Life"} subtitle_1={"私を導くのは私自身"} subtitle_2={"健やかに自由で美しく"} 
                contents_first={"【心】潜在的な治癒力や能力を活性させ、心身の深い部分からの目覚めと解放への導き、自分自身を癒し本来の輝きを取り戻せます。"}
                contents_middle={"【身】ヨガと融合させること体幹分及び軸を整え機能的な使い方のアドバイス"}
                contents_final={"心身の美と健康のトータルサポートのお手伝いをさせていただきます。"}
      />
      <AboutMe />
      <Contact />
      <Footer />
    </div>
  )
}
